-- SaunakulaApp central Supabase/PostgreSQL schema and seed data.
-- Run this in Supabase SQL Editor before testing the cloud database branch.
-- The schema also upgrades the small teacher prototype tables if they already exist.

create extension if not exists btree_gist;

create table if not exists houses (
    id bigint generated by default as identity primary key
);

alter table houses add column if not exists app_house_id text;
alter table houses add column if not exists image text not null default '';
alter table houses add column if not exists max_guests integer not null default 1;
alter table houses add column if not exists size_m2 integer not null default 1;
alter table houses add column if not exists price_per_hour numeric(10,2) not null default 0;
alter table houses add column if not exists price_24h numeric(10,2) not null default 0;
alter table houses add column if not exists price_24h_regular numeric(10,2) not null default 0;
alter table houses add column if not exists min_hours integer not null default 4;
alter table houses add column if not exists is_active boolean not null default true;
alter table houses add column if not exists created_at timestamptz not null default now();
alter table houses add column if not exists updated_at timestamptz not null default now();

insert into houses (id, app_house_id, image, max_guests, size_m2, price_per_hour, price_24h, price_24h_regular, min_hours, is_active) values
    (1, 'soome', 'soome.jpg', 20, 85, 60, 476, 596, 4, true),
    (2, 'vene', 'vene.jpg', 40, 165, 95, 672, 841, 4, true),
    (3, 'jahimees', 'jahimees.jpg', 40, 120, 95, 672, 841, 4, true),
    (4, 'spa', 'spa.jpg', 20, 120, 75, 560, 701, 4, true)
on conflict (id) do update set
    app_house_id = excluded.app_house_id,
    image = excluded.image,
    max_guests = excluded.max_guests,
    size_m2 = excluded.size_m2,
    price_per_hour = excluded.price_per_hour,
    price_24h = excluded.price_24h,
    price_24h_regular = excluded.price_24h_regular,
    min_hours = excluded.min_hours,
    is_active = excluded.is_active,
    updated_at = now();

alter table houses alter column app_house_id set not null;
create unique index if not exists houses_app_house_id_key on houses(app_house_id);

create table if not exists house_translations (
    id bigint generated by default as identity primary key,
    house_id bigint not null references houses(id) on delete cascade,
    language text not null check (language in ('et', 'ru', 'en', 'fi')),
    title text not null,
    description text not null,
    unique (house_id, language)
);

insert into house_translations (house_id, language, title, description) values
    (1, 'et', 'Soome maja', 'Looduslikust puidust interjöör, ehtne puuküttega Soome saun, külm bassein ja kümblustünn.'),
    (1, 'ru', 'Финский дом', 'Интерьер из натурального дерева, настоящая финская сауна на дровах, холодный бассейн и купель.'),
    (1, 'en', 'Finnish House', 'Natural wood interior, real wood-fired Finnish sauna, cold pool and hot tub.'),
    (1, 'fi', 'Suomalainen talo', 'Luonnonpuinen sisustus, puulämmitteinen suomalainen sauna, kylmä allas ja kylpytynnyri.'),
    (2, 'et', 'Vene maja', 'Suur vene saun 6-tonnise ahjuga, KELO puit, kaminasaal, grillterrass ja majutus suuremale seltskonnale.'),
    (2, 'ru', 'Русский дом', 'Большая русская баня с 6-тонной печью, дерево КЕЛО, каминный зал, гриль-терраса и спальни для компании.'),
    (2, 'en', 'Russian House', 'Large Russian sauna with a 6-tonne oven, KELO wood, fireplace room, grill terrace and group accommodation.'),
    (2, 'fi', 'Venäläinen talo', 'Suuri venäläinen sauna 6-tonnisella uunilla, KELO-puu, takkahuone, grillikatos ja majoitus ryhmälle.'),
    (3, 'et', 'Jahimehe maja', 'Trofeede ja vana jahistiiliga maja, KELO puidust vene saun, bassein ja grillterrass.'),
    (3, 'ru', 'Дом охотника', 'Дом с охотничьим интерьером, русская баня из дерева КЕЛО, бассейн и гриль-терраса.'),
    (3, 'en', 'Hunter''s Lodge', 'Hunter-style house with trophies, Russian KELO wood sauna, cold pool and grill terrace.'),
    (3, 'fi', 'Metsästäjän talo', 'Metsästystyylinen talo, venäläinen KELO-puusauna, kylmä allas ja grillikatos.'),
    (4, 'et', 'SPA maja', 'Kolm eri sauna: puuküttega Soome saun, aurusaun ja infrapunasaun. Lisaks bassein, kümblustünn ja karaoke.'),
    (4, 'ru', 'СПА дом', 'Три сауны: финская на дровах, паровая и инфракрасная. Также бассейн, купель и караоке.'),
    (4, 'en', 'SPA House', 'Three saunas: wood-fired Finnish sauna, steam room and infrared sauna. Also pool, hot tub and karaoke.'),
    (4, 'fi', 'SPA-talo', 'Kolme saunaa: puulämmitteinen sauna, höyrysauna ja infrapunasauna. Lisäksi allas, kylpytynnyri ja karaoke.')
on conflict (house_id, language) do update set
    title = excluded.title,
    description = excluded.description;

create table if not exists house_amenities (
    id bigint generated by default as identity primary key,
    house_id bigint not null references houses(id) on delete cascade,
    language text not null check (language in ('et', 'ru', 'en', 'fi')),
    sort_order integer not null default 0,
    text text not null
);

delete from house_amenities;
insert into house_amenities (house_id, language, sort_order, text) values
    (1, 'et', 1, 'Puuküttega Soome saun'), (1, 'et', 2, 'Kümblustünn'), (1, 'et', 3, 'Jaheda veega bassein'), (1, 'et', 4, 'Köök + kohvimasin'),
    (1, 'ru', 1, 'Финская сауна на дровах'), (1, 'ru', 2, 'Горячая купель'), (1, 'ru', 3, 'Холодный бассейн'), (1, 'ru', 4, 'Кухня + кофемашина'),
    (1, 'en', 1, 'Wood-fired Finnish sauna'), (1, 'en', 2, 'Hot tub'), (1, 'en', 3, 'Cold pool'), (1, 'en', 4, 'Kitchen + coffee machine'),
    (1, 'fi', 1, 'Puulämmitteinen sauna'), (1, 'fi', 2, 'Kylpytynnyri'), (1, 'fi', 3, 'Kylmä allas'), (1, 'fi', 4, 'Keittiö + kahvinkeitin'),
    (2, 'et', 1, '6-tonnine vene ahi'), (2, 'et', 2, 'Kümblustünn'), (2, 'et', 3, 'Neli magamistuba'), (2, 'et', 4, 'Grillterrass'),
    (2, 'ru', 1, '6-тонная русская печь'), (2, 'ru', 2, 'Горячая купель'), (2, 'ru', 3, 'Четыре спальни'), (2, 'ru', 4, 'Гриль-терраса'),
    (2, 'en', 1, '6-tonne Russian oven'), (2, 'en', 2, 'Hot tub'), (2, 'en', 3, 'Four bedrooms'), (2, 'en', 4, 'Grill terrace'),
    (2, 'fi', 1, '6-tonninen venäläinen uuni'), (2, 'fi', 2, 'Kylpytynnyri'), (2, 'fi', 3, 'Neljä makuuhuonetta'), (2, 'fi', 4, 'Grillikatos'),
    (3, 'et', 1, 'Vene saun KELO puidust'), (3, 'et', 2, 'Jaheda veega bassein'), (3, 'et', 3, 'Neli magamistuba'), (3, 'et', 4, 'Kümblustünn lisatasu eest'),
    (3, 'ru', 1, 'Русская сауна из КЕЛО'), (3, 'ru', 2, 'Холодный бассейн'), (3, 'ru', 3, 'Четыре спальни'), (3, 'ru', 4, 'Купель за доплату'),
    (3, 'en', 1, 'Russian KELO wood sauna'), (3, 'en', 2, 'Cold pool'), (3, 'en', 3, 'Four bedrooms'), (3, 'en', 4, 'Hot tub for extra fee'),
    (3, 'fi', 1, 'Venäläinen KELO-puusauna'), (3, 'fi', 2, 'Kylmä allas'), (3, 'fi', 3, 'Neljä makuuhuonetta'), (3, 'fi', 4, 'Kylpytynnyri lisämaksusta'),
    (4, 'et', 1, 'Puuküttega Soome saun'), (4, 'et', 2, 'Aurusaun'), (4, 'et', 3, 'Infrapunasaun'), (4, 'et', 4, 'Kümblustünn'),
    (4, 'ru', 1, 'Финская сауна на дровах'), (4, 'ru', 2, 'Паровая сауна'), (4, 'ru', 3, 'Инфракрасная сауна'), (4, 'ru', 4, 'Горячая купель'),
    (4, 'en', 1, 'Wood-fired Finnish sauna'), (4, 'en', 2, 'Steam room'), (4, 'en', 3, 'Infrared sauna'), (4, 'en', 4, 'Hot tub'),
    (4, 'fi', 1, 'Puulämmitteinen sauna'), (4, 'fi', 2, 'Höyrysauna'), (4, 'fi', 3, 'Infrapunasauna'), (4, 'fi', 4, 'Kylpytynnyri');

create table if not exists house_photos (
    id bigint generated by default as identity primary key,
    house_id bigint not null references houses(id) on delete cascade,
    sort_order integer not null default 0,
    url text not null
);

delete from house_photos;
insert into house_photos (house_id, sort_order, url) values
    (1, 1, 'https://saunakula.ee/wp-content/uploads/2024/07/IMG_0788-scaled.jpg'),
    (1, 2, 'https://saunakula.ee/wp-content/uploads/2024/07/IMG_0791-scaled.jpg'),
    (2, 1, 'https://saunakula.ee/wp-content/uploads/2024/06/IMG_2368-scaled.jpg'),
    (2, 2, 'https://saunakula.ee/wp-content/uploads/2024/06/IMG_2403-scaled.jpg'),
    (3, 1, 'https://saunakula.ee/wp-content/uploads/2024/07/IMG_2255-copy-scaled.jpg'),
    (3, 2, 'https://saunakula.ee/wp-content/uploads/2024/07/IMG_20201008_110001-scaled.jpg'),
    (4, 1, 'https://saunakula.ee/wp-content/uploads/2024/07/IMG_0571-scaled.jpg'),
    (4, 2, 'https://saunakula.ee/wp-content/uploads/2024/07/IMG_1003-scaled.jpg');

create table if not exists addons (
    id text primary key,
    icon text not null,
    price numeric(10,2) not null check (price >= 0),
    is_vip_free boolean not null default false,
    is_active boolean not null default true
);

create table if not exists addon_translations (
    id bigint generated by default as identity primary key,
    addon_id text not null references addons(id) on delete cascade,
    language text not null check (language in ('et', 'ru', 'en', 'fi')),
    name text not null,
    unique (addon_id, language)
);

insert into addons (id, icon, price, is_vip_free, is_active) values
    ('viht_kase', '🌿', 6, true, true),
    ('viht_tamm', '🍂', 7, true, true),
    ('lina', '🛁', 5, false, true),
    ('aroom', '🌸', 7, false, true),
    ('susi', '🔥', 7, false, true),
    ('sytik', '💧', 6, false, true),
    ('tunn', '🛁', 140, false, true)
on conflict (id) do update set
    icon = excluded.icon,
    price = excluded.price,
    is_vip_free = excluded.is_vip_free,
    is_active = excluded.is_active;

insert into addon_translations (addon_id, language, name) values
    ('viht_kase', 'et', 'Kaaseviht'), ('viht_kase', 'ru', 'Берёзовый веник'), ('viht_kase', 'en', 'Birch whisk'), ('viht_kase', 'fi', 'Koivuvihta'),
    ('viht_tamm', 'et', 'Tammeviht'), ('viht_tamm', 'ru', 'Дубовый веник'), ('viht_tamm', 'en', 'Oak whisk'), ('viht_tamm', 'fi', 'Tammivihta'),
    ('lina', 'et', 'Saunalina'), ('lina', 'ru', 'Полотенце'), ('lina', 'en', 'Sauna towel'), ('lina', 'fi', 'Saunapyyhe'),
    ('aroom', 'et', 'Saunaaroom'), ('aroom', 'ru', 'Аромат для сауны'), ('aroom', 'en', 'Sauna aroma'), ('aroom', 'fi', 'Saunaaromi'),
    ('susi', 'et', 'Grillsüsi'), ('susi', 'ru', 'Уголь для гриля'), ('susi', 'en', 'Charcoal'), ('susi', 'fi', 'Grillihiili'),
    ('sytik', 'et', 'Süütevedelik'), ('sytik', 'ru', 'Жидкость для розжига'), ('sytik', 'en', 'Lighter fluid'), ('sytik', 'fi', 'Sytytysaine'),
    ('tunn', 'et', 'Kümblustünn'), ('tunn', 'ru', 'Купель'), ('tunn', 'en', 'Hot tub'), ('tunn', 'fi', 'Kylpytynnyri')
on conflict (addon_id, language) do update set name = excluded.name;

create table if not exists reservations (
    id bigint generated by default as identity primary key,
    house_id bigint not null references houses(id),
    customer_name text not null,
    user_id bigint,
    start_date timestamptz not null,
    end_date timestamptz not null,
    guest_count integer not null default 1 check (guest_count > 0),
    total_price numeric(10,2) not null default 0 check (total_price >= 0),
    notes text not null default '',
    status text not null default 'confirmed' check (status in ('confirmed', 'cancelled')),
    created_at timestamptz not null default now(),
    check (end_date > start_date)
);

alter table reservations add column if not exists user_id bigint;
alter table reservations add column if not exists guest_count integer not null default 1;
alter table reservations add column if not exists total_price numeric(10,2) not null default 0;
alter table reservations add column if not exists notes text not null default '';
alter table reservations add column if not exists status text not null default 'confirmed';
alter table reservations add column if not exists created_at timestamptz not null default now();

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'reservations_no_overlap') then
        alter table reservations
        add constraint reservations_no_overlap
        exclude using gist (
            house_id with =,
            tstzrange(start_date, end_date, '[)') with &&
        ) where (status = 'confirmed');
    end if;
end $$;
