-- Additional domain tables for the central SaunakulaApp database.
-- Run after database/supabase-schema.sql.

create table if not exists app_users (
    id bigint generated by default as identity primary key,
    full_name text not null default '',
    email text not null unique,
    password_hash text not null default '',
    phone text not null default '',
    is_vip boolean not null default false,
    vip_granted_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists favourites (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_users(id) on delete cascade,
    house_id bigint not null references houses(id) on delete cascade,
    created_at timestamptz not null default now(),
    unique (user_id, house_id)
);

create table if not exists reservation_addons (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null references reservations(id) on delete cascade,
    addon_id text not null references addons(id),
    quantity integer not null default 1 check (quantity > 0),
    unit_price numeric(10,2) not null check (unit_price >= 0),
    created_at timestamptz not null default now(),
    unique (reservation_id, addon_id)
);

create index if not exists favourites_user_id_idx on favourites(user_id);
create index if not exists favourites_house_id_idx on favourites(house_id);
create index if not exists reservation_addons_reservation_id_idx on reservation_addons(reservation_id);
